version: "3.8"

services:
  streamlit-app:
    image: pdemeulenaer/rag-frontend:VERSION
    environment:
      - API_URL=http://api:8000/    
    restart: always
    depends_on:
      - api    

  api:
    image: pdemeulenaer/rag-backend:VERSION
    environment:
      - ALLOW_ORIGINS=*
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - QDRANT_URL=http://qdrant:6333 
    restart: always
    depends_on:
      - redis
      # - qdrant

  # qdrant:
  #   image: qdrant/qdrant
  #   restart: always
  #   volumes:
  #     - qdrant_data:/qdrant/storage


  redis:
    image: redis:7.0-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}      
  # qdrant_data: {}  
