# src/api/ingestion/poller.py

"""
DESCRIPTION OF POLLER

Step	    Action	                    Why?
Check	    Query OpenAI for Batch ID	To see if the 24h window is finished.
Download	Get .jsonl result file	    To get the GPT-generated figure descriptions.
Map	        Match custom_id with Redis	To know which PDF the description belongs to.
Embed	    Call Embedding API	        To make the description searchable by "meaning."
Upsert	    Write to Qdrant	            To make the data available for the Chatbot.
"""

import time, json, redis, logging
import openai
from openai import OpenAI
from qdrant_client import QdrantClient
import uuid
from uuid import uuid5, NAMESPACE_URL
from qdrant_client.http import models

from src.api.core.config import config
from src.api.ingestion.ingest_documents import OpenAIEmbeddings


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("poller")

# Initialize Redis & clients
r = redis.Redis(host=config.REDIS_HOST, port=config.REDIS_PORT, db=config.REDIS_DB, decode_responses=True)
client = OpenAI(api_key=config.OPENAI_API_KEY)
q_client = QdrantClient(url=config.QDRANT_URL, api_key=config.QDRANT_API_KEY)
# Log Redis connection details for debugging
logger.debug(f"🔧 Redis connection: {config.REDIS_HOST}:{config.REDIS_PORT}/{config.REDIS_DB}")

# Initialize embeddings inside poller or globally
embedding_model = OpenAIEmbeddings()

def process_completed_batch(batch_id, output_file_id):
    # 1. Use the key matching worker.py
    # Retrieve metadata map from Redis (ignore type checker warnings)
    meta_raw = r.get(f"batch_meta:{batch_id}")  # type: ignore
    if not meta_raw:
        logger.error(f"Missing metadata for batch {batch_id}")
        return
    image_metadata_map = json.loads(meta_raw)  # type: ignore

    # 2. Download results from OpenAI
    content = client.files.content(output_file_id).text
    for line in content.strip().split('\n'):
        if not line: continue
        res = json.loads(line)
        custom_id = res['custom_id']

        # Extract the description generated by OpenAI
        description = res['response']['body']['choices'][0]['message']['content']

        # Retrieve the original image info (file_hash, caption, title, etc.)
        img_info = image_metadata_map.get(custom_id)

        if img_info:
            # 3. Create the final searchable text for the figure
            # This matches the format used in ingest_documents.py
            base_info = f"Title: {img_info['title']}\n"
            full_content = f"{base_info}Figure: {img_info['caption']}\nDescription: {description}"
            
            # 4. Generate Vector for the new description
            vector = embedding_model.embed_query(full_content)
            
            # 5. Upsert as a NEW point in Qdrant
            # (In Batch mode, we add the figures after the text is already there)          
            
            # q_client.upsert(
            #     collection_name=config.QDRANT_COLLECTION_NAME,
            #     points=[
            #         models.PointStruct(
            #             id=str(uuid.uuid4()),
            #             vector=vector,
            #             payload={
            #                 "file_name": img_info["file_name"],
            #                 "file_hash": img_info["file_hash"],
            #                 "text": full_content,
            #                 "type": "figure",
            #                 "page": img_info["page_number"],
            #                 "image_path": img_info["image_filename"]
            #             }
            #         )
            #     ]
            # )

            # Generate a deterministic ID based on the custom_id from OpenAI 
            # (which we created in worker.py)
            point_id = str(uuid5(NAMESPACE_URL, f"{img_info['file_hash']}_fig_{custom_id}"))

            q_client.upsert(
                collection_name=config.QDRANT_COLLECTION_NAME,
                points=[
                    models.PointStruct(
                        id=point_id,  # Use deterministic ID here
                        vector=vector,
                        payload={
                            "file_name": img_info["file_name"],
                            "file_hash": img_info["file_hash"],
                            "file_title": img_info.get("title"), # Added for consistency
                            "authors": img_info.get("authors"),  # Added for consistency
                            "text": full_content,
                            "type": "figure",
                            "page": img_info["page_number"],
                            "image_path": img_info["image_filename"]
                        }
                    )
                ]
            )

            logger.info(f"✅ Upserted figure description for {img_info['file_name']} (Page {img_info['page_number']})")
    
    # 6. Cleanup Redis
    r.delete(f"batch_meta:{batch_id}")
    r.srem("pending_openai_batches", batch_id)

def main_loop():
    logger.info("Starting poller loop...")
    while True:
        try:
            # Get all pending batches from Redis
            # Retrieve pending batch IDs (ignore type checker warnings)
            batch_ids = r.smembers("pending_openai_batches")  # type: ignore
            
            for b_id in batch_ids:  # type: ignore
                # batch IDs are strings when decode_responses=True
                try:
                    batch = client.batches.retrieve(b_id)
                    
                    if batch.status == "completed":
                        process_completed_batch(b_id, batch.output_file_id)
                    elif batch.status in ["failed", "expired", "cancelled"]:
                        logger.error(f"Batch {b_id} ended with status: {batch.status}")
                        r.srem("pending_openai_batches", b_id) # Remove failed tasks
                
                except openai.NotFoundError:
                    logger.error(f"⚠️ Batch {b_id} not found on OpenAI. Removing from queue.")
                    r.srem("pending_openai_batches", b_id)
                except Exception as e:
                    logger.error(f"Unexpected error: {e}")

            time.sleep(30) # Wait before next poll
            
        except Exception as e:
            logger.error(f"Critical error in poller loop: {e}")
            time.sleep(10) # Wait before retrying loop

if __name__ == "__main__":
    main_loop()